core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('team.urls', namespace='team')),
    path('', include('quota.urls', namespace='quota')),
    path('', include('news.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home.views import home,about, contact

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact')
]

news/urls.py
from django.urls import path

from news.views import blog_list, blog_detail

app_name = 'news'

urlpatterns = [
    path('news/', blog_list, name='blog'),
    path('news/detail/<slug:slug>/', blog_detail, name='detail'),
]

quota/urls.py
from django.urls import path

from quota.views import quota_view


app_name = 'quota'

urlpatterns = [
    path('quota/', quota_view, name='quota_view')
]

team/urls.py
from django.urls import path

from team.views import team_view


app_name = 'team'

urlpatterns = [
    path('team/', team_view, name='team_view')
]



home/models.py
from django.db import models

class Student(models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=50)
    image = models.ImageField(upload_to='students/')
    description = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


news/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.title

class Blog(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(null=True, blank=True, unique=True, max_length=220)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(upload_to='blogs/')
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class SubImage(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blogs/')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.blog.title

def blog_pre_save(instance, sender, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)
    return instance

pre_save.connect(blog_pre_save, sender=Blog)

quota/models.py
from django.db import models


class Quota(models.Model):
    title = models.TextField()
    image = models.ImageField(upload_to='quota/')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

team/models.py
from django.db import models


class Position(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Leader(models.Model):
    fullname = models.CharField(max_length=100)
    image = models.ImageField(upload_to='leaders/')
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fullname


class Department(models.Model):
    fullname = models.CharField(max_length=100)
    image = models.ImageField(upload_to='leaders/')
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fullname

class TeamLead(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='leaders/')
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Kafedra(models.Model):
    fullname = models.CharField(max_length=100)
    image = models.ImageField(upload_to='leaders/')
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fullname

home/views.py
from django.shortcuts import render

from home.models import Student
from news.models import Blog

def home(request):
    students = Student.objects.all()
    latest_blog = Blog.objects.order_by('-id')[:3]

    context = {
        'students':students,
        'latest_blog':latest_blog
    }

    return render(request, 'index.html', context)

def about(request):
    latest_blog = Blog.objects.order_by('-id')[:3]

    context = {
        'latest_blog': latest_blog
    }
    return render(request, 'about.html', context)

def contact(request):
    latest_blog = Blog.objects.order_by('-id')[:3]

    context = {
        'latest_blog': latest_blog
    }
    return render(request, 'contact.html', context)

news/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from news.models import Blog, SubImage


def blog_list(request):
    blogs = Blog.objects.order_by('-id')

    paginator = Paginator(blogs, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'blog_list':page_obj,
        'latest_blog': blogs[:3]
    }

    return render(request, 'blog.html',context)


def blog_detail(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    latest_blog = Blog.objects.order_by('-id')[:3]

    context = {
        'blog_detail':blog,
        'latest_blog': latest_blog
    }

    return render(request, 'blog-single.html', context)

quota/views.py
from django.shortcuts import render
from news.models import Blog
from quota.models import Quota

def quota_view(request):
    quota = Quota.objects.all()
    latest_blog = Blog.objects.order_by('-id')[:3]

    context = {
        'quota':quota,
        'latest_blog': latest_blog
    }
    return render(request, 'quota.html', context)

team/views.py
from django.shortcuts import render

from team.models import Leader, Kafedra ,Department
from news.models import Blog

def team_view(request):
    leader = Leader.objects.all()
    dep = Department.objects.all()
    kafedra = Kafedra.objects.all()
    latest_blog = Blog.objects.order_by('-id')[:3]

    context = {
        'leader':leader,
        'dep':dep,
        'kafedra':kafedra,
        'latest_blog': latest_blog
    }
    return render(request, 'team.html', context)

templates/blog-single.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/fon3.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 pt-5 mt-5 text-center">
                <p class="breadcrumbs"><span class="me-2"><a href="{% url 'home:home' %}">Asosiy sahifa <i
                        class="fa fa-chevron-right"></i></a></span> <span class="me-2"><a href="{% url 'news:blog' %}">Yangiliklar <i
                        class="fa fa-chevron-right"></i></a></span> <span>Batafsil<i
                        class="fa fa-chevron-right"></i></span></p>
                <h1 class="mb-0 bread">Batafsil</h1>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section">
    <div class="container" id="blog_detail">
        <div class="row g-lg-5">
            <div class="col-lg-8 blog-single">
                <h2 class="mb-3">{{ blog_detail.title }}</h2>
                <p>
                    <img src="{{ blog_detail.image.url }}" alt class="img-fluid">
                </p>
                <p>
                    {{ blog_detail.body }}
                </p>
                {% for subimage in blog_detail.subimage_set.all %}
                <p>
                    <img src="{{ subimage.image.url }}" alt class="img-fluid">
                </p>
                {% endfor %}
                <span>{{ blog_detail.created_at|date:"d-M.Y" }}</span>
            </div>
            <div class="col-lg-4 sidebar pl-md-4">
                <div class="sidebar-box bg-light rounded">
                    <form action="#" class="search-form">
                        <div class="form-group">
                        </div>
                    </form>
                </div>

                <div class="sidebar-box">
                    <h3>So'ngi yangiliklar</h3>
                    {% for i in latest_blog %}
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img me-4" href="{% url 'news:detail' i.slug %}#blog_detail" style="background-image: url({{ i.image.url }});"></a>
                        <div class="text">
                            <span>{{ i.category }}</span>
                            <h3 class="heading"><a href="{% url 'news:detail' i.slug %}#blog_detail">{{ i.title }}</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="fa fa-calendar"></span> {{ i.created_at|date:"d-M.Y" }}</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/fon5.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 pt-5 mt-5 text-center">
                <p class="breadcrumbs"><span class="me-2"><a href="{% url 'home:home' %}">Asosiy sahifa<i
                        class="fa fa-chevron-right"></i></a></span> <span>Yangiliklar<i
                        class="fa fa-chevron-right"></i></span></p>
                <h1 class="mb-0 bread">Yangiliklar</h1>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section" id="blog_lists">
    <div class="container-xl">
        <div class="row justify-content-center">
            {% for blog in blog_list %}
                <div class="col-md-6 col-lg-4 d-flex">
                <div class="blog-entry justify-content-end" data-aos="flip-right" data-aos-duration="1000"
                     data-aos-delay="100">
                    <a href="{% url 'news:detail' blog.slug %}#blog_detail" class="block-20 img"
                       style="background-image: url({{ blog.image.url }});">
                    </a>
                    <div class="text">
                        <p class="meta"><span><i class="fa fa-user me-1"></i>{{ blog.category }}</span> <span><i
                                class="fa fa-calendar me-1"></i>{{ blog.created_at|date:"d-M.Y" }}</span> <span><a href="#">
                        <h3 class="heading mb-3"><a href="{% url 'news:detail' blog.slug %}#blog_detail">{{ blog.title }}</a></h3>
                        <p>{{ blog.body|safe|slice:"70" }}...</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% include 'paginator.html' %}
    </div>
</section>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/yon8.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 pt-5 mt-5 text-center">
                <p class="breadcrumbs"><span class="me-2"><a href="{% url 'home:home' %}">Asosiy sahifa<i
                        class="fa fa-chevron-right"></i></a></span> <span>Kontakt<i
                        class="fa fa-chevron-right"></i></span></p>
                <h1 class="mb-0 bread">Kontakt</h1>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section bg-light">
    <div class="container">
        <div class="row no-gutters justify-content-center">
            <div class="col-md-12">
                <div class="wrapper">
                    <div class="row g-0">
                        <div class="col-lg-5">
                            <h1 align="center" class="mt-6">Bizning manzil <br>xaritada!</h1>
                        </div>
                        <div class="col-lg-6">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6141.132148766326!2d66.98087355869143!3d39.681974600000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f4d188f4290b7ef%3A0x4989bc6bc98b7f36!2sAcademic%20Lyceum%20at%20the%20Medical%20Institute%20of%20Samarkand!5e0!3m2!1sru!2s!4v1697568419102!5m2!1sru!2s"
                                    width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                                    referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
                        <div class="col-lg-7 order-lg-last">
                            <div class="contact-wrap w-100 p-md-5 p-4">
                                <h3>Kontakt</h3>
                                <p class="mb-4"></p>
                                <div class="row mb-4">
                                    <div class="col-md-4">
                                        <div class="dbox w-100 d-flex align-items-start">
                                            <div class="text">
                                                <p>
                                                    <span>Manzil:</span> V Abdullayev ko'chasi 14-uy
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="dbox w-100 d-flex align-items-start">
                                            <div class="text">
                                                <p><span>Telfon raqam:</span> +998 66 232 23 58</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="dbox w-100 d-flex align-items-start">
                                            <div class="w-100 social-media">
                                                <p>
                                                    <span>Facebookdagi sahifamiz!</span>
                                                    <a href="https://www.facebook.com/groups/267207672254996/">Havola</a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/footer.html
{% load static %}

<footer class="ftco-footer">
    <div class="container-xl">
        <div class="row mb-5 justify-content-between">
            <div class="col-md-6 col-lg">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2 logo d-flex">
                        <a class="navbar-brand align-items-center" href="index-2.html">
                            Akademik litsey
                            <span>SamDTU qoshidagi akademik litsey</span>
                        </a>
                    </h2>
                    <p>
                        Barcha huquqlar himoyalangan. Saytdagi barcha huquqlar O'zbekiston Respublikasi qonunlariga,
                        shu jumladan mualliflik huquqi va turdosh huquqlarga muvofiq himoya qilinadi.
                    </p>
<!--                    <ul class="ftco-footer-social list-unstyled mt-2">-->
<!--                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>-->
<!--                        <li><a href="#"><span class="fa fa-facebook"></span></a></li>-->
<!--                        <li><a href="#"><span class="fa fa-instagram"></span></a></li>-->
<!--                    </ul>-->
                </div>
            </div>
            <div class="col-md-6 col-lg-2">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Bo'limlar</h2>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'home:about' %}"><span class="ion ion-ios-arrow-round-forward me-2"></span>Biz haqimizda</a></li>
                        <li><a href="{% url 'news:blog' %}"><span class="ion ion-ios-arrow-round-forward me-2"></span>Yangiliklar</a></li>
                        <li><a href="{% url 'team:team_view' %}"><span class="ion ion-ios-arrow-round-forward me-2"></span>Jamoa</a></li>
                        <li><a href="{% url 'quota:quota_view' %}"><span class="ion ion-ios-arrow-round-forward me-2"></span>Qabul</a></li>
                        <li><a href="{% url 'home:contact' %}"><span class="ion ion-ios-arrow-round-forward me-2"></span>Kontakt</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-lg">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">So'ngi yangiliklar</h2>
                    {% for i in latest_blog %}
                        <div class="block-21 mb-4 d-flex">
                        <a class="blog-img img rounded" href="{% url 'news:detail' i.slug %}#blog_detail" style="background-image: url('{{ i.image.url }}');"></a>
                        <div class="text">
                            <div class="meta">
                                <div><a href="#"><span class="fa fa-calendar"></span>{{ i.created_at|date:"M.d.Y" }}</a></div>
                                <div><a href="#"><span class="fa fa-user"></span> Admin</a></div>
                            </div>
                            <h3 class="heading"><a href="{% url 'news:detail' i.slug %}#blog_detail">{{ i.title }}</a></h3>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-6 col-lg">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Manzil</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon fa fa-map marker"></span><span class="text">
                                Vohid Abdullayev ko'chasi, 14-uy. Samarqand sh.</span>
                            </li>
                            <li><a href="#"><span class="icon fa fa-phone"></span><span
                                    class="text">+998 66 232 23 58</span></a></li>
<!--                            <li><a href="#"><span class="icon fa fa-paper-plane"></span><span class="text"><span-->
<!--                                    class="__cf_email__" data-cfemail="771e191118370e18020513181a161e195914181a">[email&#160;protected]</span></span></a>-->
<!--                            </li>-->
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid px-0 py-5 bg-darken">
        <div class="container-xl">
            <div class="row">
                <div class="col-md-12 text-center">
                    <p class="mb-0" style="font-size: 14px;">Copyright &copy;<script data-cfasync="false"
                                                                                     src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                        <script>document.write(new Date().getFullYear());</script>
                        All rights reserved | This template is made with <i class="fa fa-heart color-danger"
                                                                            aria-hidden="true"></i> by <a
                                href="https://colorlib.com/" target="_blank" rel="nofollow noopener">Colorlib</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}

<header>
    <div class="top-wrap home-head">
        <div class="container">
            <div class="row">
                <div class="col-md col-xl-5 d-flex align-items-center">
                    <a class="navbar-brand align-items-center" href="{% url 'home:home' %}">
                        SamDTU AL
                    </a>
                </div>
                <div class="col-md d-flex justify-content-end align-items-center">
                    <div class="con d-flex">
                        <div class="text">
                        </div>
                    </div>
                </div>
                <div class="col-md d-flex align-items-center">
                    <div class="con d-flex">
                        <div class="icon"><span class="flaticon-clock"></span></div>
                        <div class="text">
                            <span>Dushanba - Shanba</span>
                            <strong>8:00-17:00</strong>
                        </div>
                    </div>
                </div>
                <div class="col-md d-flex align-items-center">
                    <div class="con d-flex" style="color: #000">
                        <div class="icon"><span class="flaticon-telephone"></span></div>
                        <div class="text">
                            <span>Telfon raqam</span>
                            <strong>+998 66 232 23 58</strong>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg  ftco-navbar-light">
        <div class="container-xl">

            <a href="#" class="btn-custom order-lg-last">Akademik litsey</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fa fa-bars"></span> Menu
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}">Asosiy</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'news:blog' %}">Yangiliklar</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'home:about' %}">Biz haqimizda</a></li>
                    <li class="nav-item dropdown me-auto mb-2 mb-lg-0" type="button">
                        <a class="nav-link btn btn-secondary dropdown-toggle" type="button"
                           href="{% url 'team:team_view' %}" style="font-size:15px; position: relative; top: 1.7px; text-transform: capitalize">Tuzilma</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'team:team_view' %}#leader">Rahbariyat</a></li>
                            <li><a class="dropdown-item" href="{% url 'team:team_view' %}#department">Bo'lim</a></li>
                            <li><a class="dropdown-item" href="{% url 'team:team_view' %}#kafedra">Kafedra</a></li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'quota:quota_view' %}">Qabul</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'home:contact' %}">Kontaktlar</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/paginator.html
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    <ul>
                        {% if blog_list.has_previous %}
                            <li><a href="?page={{ objects.previous_page_number }}#blog_lists">&lt;</a></li>
                        {% endif %}

                        {% for i in blog_list.paginator.page_range %}
                            {% if i == blog_list.number %}
                                <li class="active"><span>{{ i }}</span></li>
                            {% else %}
                                <li><a href="?page={{ i }}#blog_lists">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if blog_list.has_next %}
                            <li><a href="?page={{ blog_list.next_page_number }}#blog_lists">&gt;</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>



templates/quota.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/yon8.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 pt-5 mt-5 text-center">
                <p class="breadcrumbs"><span class="me-2"><a href="{% url 'home:home' %}">Asosiy sahifa<i
                        class="fa fa-chevron-right"></i></a></span> <span>Qabul<i
                        class="fa fa-chevron-right"></i></span></p>
                <h1 class="mb-0 bread">Akademik litsey qabul jadvali</h1>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section courses-section ftco-no-pb">
    <div class="container">
        <div class="row justify-content-center pb-4">
            <div class="col-md-10 text-center heading-section" data-aos="fade-up">
                <span class="subheading">Qabul</span>
            </div>

            {% for q in quota%}
                <img src="{{ q.image.url }}">
            {% endfor %}
        </div>
    </div>
</section>
<section class="ftco-section ftco-no-pt">
    <div class="row justify-content-center pb-5">
        <div class="col-md-7 text-center heading-section" data-aos="fade-up" data-aos-duration="1000">
            <span class="subheading">FAQ</span>
            <h2 class="mb-3">Ko'p so'raladigan savollar</span></h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8" data-aos="fade-up" data-aos-duration="1000">
            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Qabul kunlari qachon bo'ladi?
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
                         data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            Qabul kunlari har yili<strong>15-iyundan 15-iyulgacha</strong> bo'ladi.
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingTwo">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Where It is hidden by default, until the collapse?
                        </button>
                    </h2>
                    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
                         data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            It is hidden by default, until the collapse plugin adds the appropriate classes that we use
                            to style each element. It's also worth noting that just about any HTML can go within the
                            <code>.accordion-body</code>, though the transition does limit overflow.
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingThree">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            How It is hidden by default, until the collapse?
                        </button>
                    </h2>
                    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
                         data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            It is hidden by default, until the collapse plugin adds the appropriate classes that we use
                            to style each element. It's also worth noting that just about any HTML can go within the
                            <code>.accordion-body</code>, though the transition does limit overflow.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}